ROW_LIMIT = 5000
SUPERSET_WEBSERVER_PORT = 8088
SUPERSET_WEBSERVER_ADDRESS = '0.0.0.0'
SUPERSET_WEBSERVER_TIMEOUT = 300
SUPERSET_SQLLAB_TIMEOUT = 300
SECRET_KEY = '7av;{I^uQLeJ32:5$B2:&dE.o#&Lae(N'



SESSION_COOKIE_SAMESITE = "Lax"